### ISSUE TITLE
Approved as Flower Tier but Dashboard Still Shows "Spore"

### ISSUE THREAD

**Issue by doasinfinity** [pollinations/pollinations#5762]
Hi, my account has already been approved as Flower tier as confirmed in this comment:
https://github.com/pollinations/pollinations/issues/2934#issuecomment-3360488544

However, when I sign in to the dashboard at https://enter.pollinations.ai/ , my account tier is still shown as Spore, not Flower.

Could you please help update or sync my account tier?
Thank you! 🙏

**Comment by voodoohop** [comment]
Hey @doasinfinity! 🌸

We've upgraded your account to Flower tier in both our database and Polar subscription system. Your dashboard should now show Flower tier correctly.

Sorry for the delay - the tier wasn't synced properly after your app approval. All fixed now!

Enjoy! ✨

**Comment by doasinfinity** [comment]
> Hey [@doasinfinity](https://github.com/doasinfinity)! 🌸
> 
> We've upgraded your account to Flower tier in both our database and Polar subscription system. Your dashboard should now show Flower tier correctly.
> 
> Sorry for the delay - the tier wasn't synced properly after your app approval. All fixed now!
> 
> Enjoy! ✨

Hi @voodoohop,

Thanks for the update! I just checked on https://enter.pollinations.ai/ and my tier is still showing as "Spore" instead of "Flower".
Any idea what might be causing this?

Let me know if you need anything from my side. Thanks again! 🙏✨

Thanks
